### ISSUE TITLE
Update parsing logic to workaround Yahoo Finances webpage changes

### ISSUE THREAD

**Issue by kennardpeters** [kennardpeters/rust_options_analyzer#25]
- Yahoo recently changed their page load logic (looks like they migrated to svelte, thus breaking our preexisting scraping logic)
- May need to add retry logic or a work around such as [this](https://medium.com/geekculture/scraping-a-dynamic-website-without-selenium-part-i-c1fec0d302bd)
- May need to use [thirtyfour](https://stevepryde.github.io/thirtyfour/getting-started/first-code.html)

### Tasks
- [x] Fix request headers
- [x] Generate request headers dynamically
- [x] Add better data validation
- [x] #27

### References
- [Pulling environment variables in Rust](https://siciarz.net/24-days-rust-environment-variables/#:~:text=The%20simplest%20way%20to%20access,to%20read%20current%20language%20setting.)
